name: Get Bing Wallpaper

on:
  schedule:
    - cron: '0 16 * * *' # 每天下午4点运行 (UTC时间)
  push:
    paths:
      - '.github/**' # 监听 .github 文件夹的修改
  workflow_dispatch: # 添加 workflow_dispatch 触发器，手动触发工作流程

jobs:
  get_recent_wallpapers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Create folders
      run: |
        mkdir -p wallpapers

    - name: Download Recent Bing Wallpapers
      run: |
        for ((i=0; i<7; i++)); do
          IMAGE_URL=$(curl -sL "https://www.bing.com/HPImageArchive.aspx?idx=$i&n=1&format=js" | jq -r '.images[0].url')
          FULL_IMAGE_URL="https://www.bing.com$IMAGE_URL"
          echo "Downloading Bing Wallpaper for Day $i: $FULL_IMAGE_URL"
          wget "$FULL_IMAGE_URL" -P "wallpapers/"
        done

    - name: Commit and push changes
      run: |
        git config --local user.email "markwalsh6809@gmail.com" # 替换为您的 GitHub 邮箱地址
        git config --local user.name "RashidaKAKU" # 替换为您的 GitHub 用户名
        git add wallpapers/*
        git commit -m "Add recent Bing wallpapers"
        git push origin main # 假设主分支为 main，请根据实际情况替换为您的主分支名称

