jobs:
  get_4k_wallpaper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Create folders
      run: |
        mkdir -p wallpapers
        YEAR_MONTH=$(date +%Y/%m)
        mkdir -p "wallpapers/$YEAR_MONTH"

    - name: Get 4K Bing Wallpaper URL
      run: |
        IMAGE_URL=$(curl -sL "https://www.bing.com/HPImageArchive.aspx?format=js&n=1&mkt=en-US" | jq -r '.images[] | select(.wp == "YES") | .url')
        FULL_IMAGE_URL="https://www.bing.com$IMAGE_URL"
        echo "Downloading 4K Wallpaper: $FULL_IMAGE_URL"

    - name: Download 4K Bing Wallpaper
      run: |
        wget -q "$FULL_IMAGE_URL" -P "wallpapers/$YEAR_MONTH"

    - name: Commit and push changes
      run: |
        git config --local user.email "markwalsh6809@gmail.com" # 替换为您的 GitHub 邮箱地址
        git config --local user.name "RashidaKAKU" # 替换为您的 GitHub 用户名
        git add wallpapers/*
        git commit -m "Add 4K Bing wallpaper for $(date +'%Y/%m/%d')"
        git push origin main # 假设主分支为 main，请根据实际情况替换为您的主分支名称
