name: Get Bing Wallpaper

on:
  schedule:
    - cron: '0 16 * * *' # 每天下午4点运行 (UTC时间)
  push:
    paths:
      - '.github/**' # 监听 .github 文件夹的修改
  workflow_dispatch: # 添加 workflow_dispatch 触发器，手动触发工作流程

jobs:
  get_today_wallpaper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Create folders
      run: |
        YEAR_MONTH_DAY=$(date +%Y/%m/%d)
        mkdir -p "wallpapers/$YEAR_MONTH_DAY"

    - name: Download Today's Bing Wallpaper
      run: |
        IMAGE_URL=$(curl -sL "https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US" | jq -r '.images[0].url')
        FULL_IMAGE_URL="https://www.bing.com$IMAGE_URL"
        FILENAME=$(date +'%Y%m%d').jpg
        echo "Downloading Bing Wallpaper: $FULL_IMAGE_URL"
        wget -q -O "wallpapers/$YEAR_MONTH_DAY/$FILENAME" "$FULL_IMAGE_URL"

    - name: Commit and push changes
      run: |
        git config --local user.email "markwalsh6809@gmail.com" # 替换为您的 GitHub 邮箱地址
        git config --local user.name "RashidaKAKU" # 替换为您的 GitHub 用户名
        git add wallpapers/*
        git commit -m "Add Bing wallpaper for $(date +'%Y/%m/%d')"
        git push origin main # 假设主分支为 main，请根据实际情况替换为您的主分支名称

